### ISSUE TITLE
SML: CreateProcess failed

### ISSUE THREAD

**Issue by MartinAskestad** [benknoble/vim-simpl#5]
I'm running Vim 9.1 on Windows 11, I just installed Standard ML of New Jersey and running the repl `sml` directly in command line works fine. But through vim-simpl plugin I get the error message "CreateProcess failed".

Could this be because sml is a bat file on Windows? And perhaps Vim doesn't like bat-files? I've tried running Racket repl using vim-simpl and it works great.

**Comment by benknoble** [comment]
Can you share more details? For example
- what is `b:interpreter` while editing your SML file?
- what `simpl#` function are you calling that fails?
- is the `sml` executable on the Windows equivalent of PATH while you're running Vim?

**Comment by MartinAskestad** [comment]
It's `sml` and I `call simpl#repl()` and yes.

If I open a terminal and type sml and press enter the repl starts just fine, if I run the command `:term sml` I get the same CreateProcess error, so it really seems like Vim doesn't like bat-files.

**Comment by benknoble** [comment]
Ah, if `:terminal sml` doesn't work, this plugin can't.

Perhaps `++shell` will help?

**Comment by MartinAskestad** [comment]
You know what, setting `b:interpreter` to the command that the bat-file is calling works.

`let b:interpreter='"C:\Program Files (x86)\SMLNJ\\bin\.run\run.x86-win32.exe" "@SMLload=C:\Program Files (x86)\SMLNJ\\bin\.heap\sml"'`
